# Generated by Django 4.2.17 on 2025-02-12 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0004_alter_purchasereturn_order'),
        ('sales', '0010_alter_salesorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('record_number', models.CharField(max_length=255, unique=True, verbose_name='收款记录编号')),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售金额')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder', verbose_name='销售订单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '收款记录',
                'verbose_name_plural': '收款记录列表',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('record_number', models.CharField(max_length=255, unique=True, verbose_name='付款记录编号')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='付款金额')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder', verbose_name='采购订单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录列表',
                'ordering': ['created_at'],
            },
        ),
    ]
