# Generated by Django 4.2.17 on 2025-02-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptrecord',
            name='receipt_amount',
        ),
    ]
