# Generated by Django 4.2.17 on 2025-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_receiptrecord_receipt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='付款金额/应付金额*100'),
            preserve_default=False,
        ),
    ]
