# Generated by Django 4.2.17 on 2025-02-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_paymentrecord_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '付款记录', 'verbose_name_plural': '付款记录列表'},
        ),
    ]
