# Generated by Django 4.2.17 on 2025-01-21 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0006_remove_productionline_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0010_alter_salesorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialrequisition_number', models.CharField(max_length=100, unique=True, verbose_name='领料单编号')),
            ],
            options={
                'verbose_name': '领料单',
                'verbose_name_plural': '领料单',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='工单编号')),
                ('planned_start_time', models.DateTimeField(verbose_name='计划开工时间')),
                ('planned_end_time', models.DateTimeField(verbose_name='计划完工时间')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='负责人')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('material_collected', '已领料'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.productionline', verbose_name='产线')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder', unique=True, verbose_name='销售订单')),
            ],
            options={
                'verbose_name': '生产工单',
                'verbose_name_plural': '生产工单列表',
                'ordering': ['planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.material', verbose_name='原材料')),
                ('materialrequisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.materialrequisition', verbose_name='领料单')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='production_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.productionorder', verbose_name='生产工单'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='responsible_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
