# Generated by Django 4.2.17 on 2025-01-20 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequisition',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='responsible_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
