# Generated by Django 4.2.17 on 2025-01-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_remove_productionline_capacity_and_more'),
        ('production', '0002_warehousingreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预期入库数量')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际入库数量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.product', verbose_name='产品')),
                ('warehousingreceipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.warehousingreceipt', verbose_name='入库单')),
            ],
        ),
    ]
