# Generated by Django 4.2.17 on 2025-01-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder', unique=True, verbose_name='采购订单'),
        ),
    ]
