# Generated by Django 3.2.25 on 2024-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='容量'),
        ),
    ]
