# Generated by Django 4.2.17 on 2025-01-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_product_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='产线名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='生产能力 (单位/小时)')),
                ('status', models.CharField(choices=[('active', '运行中'), ('inactive', '停用')], default='active', max_length=50, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
