# Generated by Django 4.2.17 on 2025-02-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_remove_productionline_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_number',
            field=models.CharField(default='RP-000001', max_length=255, unique=False, verbose_name='配方编号'),
            preserve_default=False,
        ),
    ]
