# Generated by Django 4.2.17 on 2025-02-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_recipe_recipe_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_number',
            field=models.CharField(max_length=255, verbose_name='配方编号'),
        ),
    ]
