# Generated by Django 4.2.17 on 2025-02-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_alter_recipe_recipe_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_number',
        ),
    ]
