# Generated by Django 4.2.17 on 2025-02-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_remove_recipe_recipe_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_number',
            field=models.CharField(default='RP-00001', max_length=255, verbose_name='配方编号'),
            preserve_default=False,
        ),
    ]
