# Generated by Django 4.2.17 on 2025-02-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_recipe_recipe_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='配方编号'),
        ),
    ]
