# Generated by Django 5.1.3 on 2024-11-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delivery_number', models.CharField(max_length=255, unique=True, verbose_name='出库单编号')),
                ('date', models.DateField(auto_now_add=True, verbose_name='出库日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_number', models.CharField(max_length=255, unique=True, verbose_name='订单编号')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('shipped', '已出库'), ('returned', '已退库')], default='pending', max_length=50, verbose_name='订单状态')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('return_number', models.CharField(max_length=255, unique=True, verbose_name='退库单编号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退货数量')),
                ('date', models.DateField(auto_now_add=True, verbose_name='退货日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
