# Generated by Django 5.1.3 on 2024-11-29 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='客户合同号'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_time',
            field=models.DateField(blank=True, null=True, verbose_name='交付时间'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已付金额'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='销售金额'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='销售员'),
        ),
    ]
