# Generated by Django 5.1.3 on 2024-11-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_contract_number_salesorder_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
