# Generated by Django 5.1.3 on 2024-11-29 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='客户合同号'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已付金额'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sales_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售金额'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='salesperson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='销售员'),
            preserve_default=False,
        ),
    ]
