# Generated by Django 5.1.3 on 2024-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_salesorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('shipped', '已出库'), ('returned', '已退库')], default='pending', max_length=50, verbose_name='订单状态'),
        ),
    ]
