# Generated by Django 4.2.17 on 2025-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('shipped', '已出库'), ('returned', '已退库'), ('produced', '已生产'), ('scheduled', '已排产')], default='pending', max_length=50, verbose_name='订单状态'),
        ),
    ]
